#pragma once

#define _1_ void
#define _2_ std
#define _3_ ;
#define _4_ return
#define _5_ {
#define _6_ }
#define _7_ int
#define _8_ main
#define _9_ 0
#define _10_ cout
#define _11_ <<
#define _12_ >>
#define _13_ endl
#define _14_ <iostream>
#define _15_ while
#define _16_ true
#define _17_ <string>
#define _18_ string
#define _19_ input
#define _20_ input_value
#define _21_ <cstdlib>
#define _22_ atoi
#define _23_ =
#define _24_ c_str
#define _25_ for
#define _26_ sum
#define _27_ i
#define _28_ --
#define _29_ +=
#define _30_ >
#define _31_ if
#define _32_ ==
#define _33_ "exit"
#define _34_ cin
#define _35_ endl
#define _36_ long